### ISSUE TITLE
URL to Modelplatform/Server is hardcoded 

### ISSUE THREAD

**Issue by herzogrh** [citysciencelab/scenario-explorer-addon#69]
It seems that [here](https://github.com/citysciencelab/scenario-explorer-addon/blob/main/simulationTool/store/actions.js) the fetch queries to the Urban Model Platform are hardcoded. 

In the MP [configuration file](https://github.com/citysciencelab/scenario-explorer-portalconfig/blob/main/config.js)  is an attribute `simulationApiUrl: "http://localhost/api",` which lets users define the endpoint of the UMP. This configuration should be used for all communication to the UMP.

**Comment by herzogrh** [comment]
After more checking, it seems hardcoded in more or less every vue component as well.

**Comment by hwbllmnn** [comment]
Yes, after some tests we found out that for some unknown reason vuejs replaces the configured url with `http://localhost` when we access it in the components. That's why we changed the code to use paths instead of full urls, see https://github.com/citysciencelab/scenario-explorer-addon/pull/28

The reasoning is that since the UMP is practically (mostly) a proxy for model servers anyway it makes a lot of sense to assume that the client is served from the same server where the proxy runs. This is also good practice to avoid CORS errors in the client.

**Comment by herzogrh** [comment]
Thanks, that makes sense. But as the simulation addon can be added to multiple Masterportal instances which run on various domains the URL to UMP should be configurable in the config.js because otherwise, there would only be a single MP instance which could have the simulation AddOn.
